;; automatically generated by
;; CONSFIGURATOR::DUMP-PROPERTIES-FOR-EMACS; do not edit

(put 'consfigurator:deploys. 'common-lisp-indent-function '2)
(put 'consfigurator:deploys-these. 'common-lisp-indent-function '2)
(put 'file:has-content 'common-lisp-indent-function '1)
(put 'file:has-content. 'common-lisp-indent-function '1)
(put 'file:contains-lines. 'common-lisp-indent-function '1)
(put 'file:data-uploaded. 'common-lisp-indent-function '2)
(put 'file:secret-uploaded. 'common-lisp-indent-function '2)
(put 'file:regex-replaced-lines. 'common-lisp-indent-function '2)
(put 'os:debian-stable. 'common-lisp-indent-function '1)
(put 'chroot:%os-bootstrapped. 'common-lisp-indent-function '2)
